name: Build and Package
on: push

jobs:
  build-windows:
    name: build for windows-2019
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install python dependencies
        run: |
            python -m pip install --upgrade pip
            pip install wheel
            pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
      - name: package binary
        run: |
          python -m PyInstaller --clean pyinstaller/pyinstaller.spec
      - name: publish binary
        uses: actions/upload-artifact@master
        with:
          name: ticronem_windows
          path: dist/ticronem.exe
  build-osx:
    name: build for macos-10.15
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
      - name: package binary and rename
        run: |
          pyinstaller --clean pyinstaller/mac-os.spec
          mv dist/ticronem dist/ticronem_macosx
      - name: Bash Command Lines for GitHub Actions
        run: chmod +x dist/ticronem_macosx
        shell: bash
      - name: publish binary
        uses: actions/upload-artifact@master
        with:
          name: ticronem_macosx
          path: dist/ticronem_macosx
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/release')
    name: Publish release to github
    runs-on: ubuntu-18.04
    needs: [build-osx, build-windows]
    steps:
      - name: Download osx artifact
        uses: actions/download-artifact@v1
        with:
          name: ticronem_macosx
      - name: Download windows artifact
        uses: actions/download-artifact@v1
        with:
          name: ticronem_windows
      - name: Trimming tag
        id: trimmer
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/release/}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.trimmer.outputs.tag }}
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "ticronem_windows/ticronem.exe, ticronem_macosx/ticronem_macosx"