# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  build-ubuntu:
    name: Build for ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install apt dependencies
      run: |
        sudo apt update
        sudo apt install -y $(cat apt_dependencies.txt)
    - name: install python dependencies
      run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
